version: "3"

services:
  app:
    build:
      context: .
    ports:
      - 8000:8000
    depends_on:
      - db
    restart: on-failure
    command: sh -c 'sleep 10 && python main.py'
  db:
    image: postgres:latest
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: university
    volumes:
      - ./sql/01_create_roles.sql:/docker-entrypoint-initdb.d/01_create_roles.sql
      - ./sql/02_schema.sql:/docker-entrypoint-initdb.d/02_schema.sql
      - ./sql/03_initial_data.sql:/docker-entrypoint-initdb.d/03_initial_data.sql